### ISSUE TITLE
uninitialized constant RSpec::Core::Hooks

### ISSUE THREAD

**Issue by dipth** [MrJoy/rspec-gc-control#2]
I'm getting the following error:

```
uninitialized constant RSpec::Core::Hooks
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-core-2.14.3/lib/rspec/core/configuration.rb:32:in `<class:Configuration>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-core-2.14.3/lib/rspec/core/configuration.rb:31:in `<module:Core>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-core-2.14.3/lib/rspec/core/configuration.rb:7:in `<module:RSpec>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-core-2.14.3/lib/rspec/core/configuration.rb:6:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-gc-control-1.0.1/lib/rspec-gc-control/configuration.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rspec-gc-control-1.0.1/lib/rspec-gc-control.rb:3:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/home/travis/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/home/travis/build/gfish/naoshi/config/application.rb:7:in `<top (required)>'
/home/travis/build/gfish/naoshi/Rakefile:5:in `require'
/home/travis/build/gfish/naoshi/Rakefile:5:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:637:in `raw_load_rakefile'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:94:in `block in load_rakefile'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:93:in `load_rakefile'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:77:in `block in run'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/bin/rake:23:in `load'
/home/travis/.rvm/gems/ruby-1.9.3-p448/bin/rake:23:in `<main>'
/home/travis/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by cbliard** [comment]
Same problem here (using rspec-core 2.12.2). I had to modify the gem to require some other files

In file `lib/rspec-gc-control/configuration.rb`, add some `require`

```
require 'rspec/core/metadata_hash_builder'
require 'rspec/core/hooks'
require 'rspec/core/configuration'
```

or replace them by

```
require 'rspec'
```

I can issue a pull request but I do not know if requiring 'rspec' is fine.

**Comment by MrJoy** [comment]
D'oh.  Thanks!  I will look into making this change and pushing a new version.
